# Arquivo: render.yaml
# Isso garante que todas as rotas (URLs) n√£o encontradas sejam redirecionadas para o index.html,
# permitindo que o React Router assuma o controle.

headers:
    - path: /*
      headers:
          - key: X-Frame-Options
            value: DENY
          - key: X-XSS-Protection
            value: 1; mode=block
          - key: X-Content-Type-Options
            value: nosniff
redirects:
    - from: /*
      to: /index.html
      status: 200
